openapi: 3.0.0
info:
  title: dsfef
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /login:
    get:
      summary: Your GET endpoint
      tags: []
      responses: {}
      operationId: get-login
components:
  schemas: {}
